defaults:
  - hydra: default
  - model: dyn_unet_base
  - _self_

# i/o
image_path: './input_nifti' #TODO change this if you renamed your directories
image_file_ending: nii.gz
output_folder: './output_nifti' # TODO change this if you renamed your directories
file_app: ""

mask_path: null
round_to: 2

# model & ckpt
device: cuda:0
ckpt_path: /path/to/ckpt.pt

# sliding window inferer
batch_size: 4     #TODO it was originally 16, but replaced it to be compatible with my device
patch_size: [128, 128, 128]
overlap: 0.5
mode: "constant"
sigma_scale: 0.125
padding_mode: "constant"

# eval & reproducibility
seed: 404

# standard pre-processing transforms
transforms_config:
  - EnsureChannelFirst:
      channel_dim: "no_channel"
  - ScaleIntensityRangePercentiles:
      lower: 1
      upper: 99
      b_min: 0
      b_max: 1
      clip: true
  - ToTensor:
      device: null

# test time augmentation
tta:
  scales: [1] #[0.5, 1, 1.5]
  invert: false
  invert_mean_thresh: 0.5
  equalize_hist: false
  hist_bins: 100

# post-processing
post:
  apply: false
  small_objects_min_size: 500
  small_objects_connectivity: 3

# merging
merging:
  threshold: 0.5
  max: false